# -*- coding: utf-8 -*-
"""H.C.E.Metodos_POO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VvrfhLaT5YxPpTxeel6d0-Fs2vinhZo
"""

class Motor:
    """Clase que representa el motor de un vehículo"""

    def __init__(self, tipo, potencia):
        self._tipo = tipo
        self._potencia = potencia
        self._encendido = False

    @property
    def tipo(self):
        return self._tipo

    @tipo.setter
    def tipo(self, valor):
        self._tipo = valor

    @property
    def potencia(self):
        return self._potencia

    @potencia.setter
    def potencia(self, valor):
        if valor > 0:
            self._potencia = valor
        else:
            print("La potencia debe ser mayor a 0")

    def encender_motor(self):
        if not self._encendido:
            self._encendido = True
            print(f"Motor {self._tipo} encendido. ¡Vroom vroom! 🔥")
        else:
            print("El motor ya está encendido :D")

    def detener_motor(self):
        if self._encendido:
            self._encendido = False
            print("Motor apagado correctamente")
        else:
            print("El motor ya estaba apagado :<")

    def __str__(self):
        estado = "encendido" if self._encendido else "apagado"
        return f"Motor {self._tipo} de {self._potencia} HP (Estado: {estado})"


class Vehiculo:
    """Superclase que representa un vehículo genérico"""

    def __init__(self, marca, modelo, anio, motor):
        self._marca = marca
        self._modelo = modelo
        self._anio = anio
        self._motor = motor  # Composición: Vehiculo tiene un Motor
        self._encendido = False

    @property
    def marca(self):
        return self._marca

    @marca.setter
    def marca(self, valor):
        self._marca = valor

    @property
    def modelo(self):
        return self._modelo

    @modelo.setter
    def modelo(self, valor):
        self._modelo = valor

    @property
    def anio(self):
        return self._anio
    @anio.setter
    def anio(self, valor):
        if valor > 1900:
            self._anio = valor
        else:
            print("Año inválido")

    @property
    def motor(self):
        return self._motor
    @motor.setter
    def motor(self, valor):
        self._motor = valor

    def encender(self):
        if not self._encendido:
            self._encendido = True
            self._motor.encender_motor()
            print(f"✅ {self._marca} {self._modelo} listo para conducir")
        else:
            print("El vehículo ya está encendido :3")

    def apagar(self):
        if self._encendido:
            self._motor.detener_motor()
            self._encendido = False
            print(f"⏹️ {self._marca} {self._modelo} apagado")
        else:
            print("El vehículo ya estaba apagado :C")

    def __str__(self):
        return f"{self._marca} {self._modelo} ({self._anio})"


class Automovil(Vehiculo):
    """Clase que representa un automóvil (hereda de Vehiculo)"""

    def __init__(self, marca, modelo, anio, motor, numero_puertas):
        super().__init__(marca, modelo, anio, motor)
        self._numero_puertas = numero_puertas
        self._maletero_abierto = False

    @property
    def numero_puertas(self):
        return self._numero_puertas
    @numero_puertas.setter
    def numero_puertas(self, valor):
        if valor in [2, 3, 4, 5]:
            self._numero_puertas = valor
        else:
            print("Número de puertas inválido")

    def abrir_maletero(self):
        if not self._maletero_abierto:
            self._maletero_abierto = True
            print("🔓 *Click* Maletero abierto")
        else:
            print("El maletero ya está abierto ;D")

    def tocar_claxon(self):
        print("🔊 ¡BEEP BEEP! (el claxon suena fuerte :O)")

    def __str__(self):
        return f"{super().__str__()} - Auto de {self._numero_puertas} puertas\n   └─ {self._motor}"


class Motocicleta(Vehiculo):
    """Clase que representa una motocicleta (hereda de Vehiculo)"""

    def __init__(self, marca, modelo, anio, motor, cilindraje):
        super().__init__(marca, modelo, anio, motor)
        self._cilindraje = cilindraje

    @property
    def cilindraje(self):
        return self._cilindraje

    @cilindraje.setter
    def cilindraje(self, valor):
        if valor > 0:
            self._cilindraje = valor
        else:
            print("Cilindraje inválido")

    def hacer_caballito(self):
        if self._encendido:
            print("🏍️ ¡WHEEELIE! Rueda delantera en el aire :>")
        else:
            print("⚠️ Primero enciende la moto para hacer trucos")

    def usar_patada_arranque(self):
        print("👢 *Pateando el pedal* Intentando arranque manual...")
        if not self._encendido:
            self.encender()
        else:
            print("La moto ya está encendida :D")

    def __str__(self):
        return f"{super().__str__()} - Moto {self._cilindraje}cc\n   └─ {self._motor}"


# Principal
def separador(titulo=""):
    print("\n" + "=" * 65)
    if titulo:
        print(f"  {titulo}")
        print("=" * 65)

def main():
    print("\n")
    print("╔" + "=" * 63 + "╗")
    print("║" + " " * 15 + "Sistema de vehiculos - " + " " * 22 + "║")
    print("╚" + "=" * 63 + "╝")

    # Motores
    separador("CREACIÓN DE MOTORES")
    motor1 = Motor("V8 Gasolina", 450)
    motor2 = Motor("Eléctrico", 300)
    motor3 = Motor("Monocilíndrico 4T", 75)
    motor4 = Motor("Bicilíndrico en paralelo", 150)

    print("✓ Motor 1:", motor1)
    print("✓ Motor 2:", motor2)
    print("✓ Motor 3:", motor3)
    print("✓ Motor 4:", motor4)

    # Autos
    separador("CREACIÓN DE AUTOMÓVILES")
    auto1 = Automovil("Chevrolet", "Camaro", 2024, motor1, 2)
    auto2 = Automovil("Tesla", "Model 3", 2023, motor2, 4)

    print(f"🚗 Automóvil 1:\n   {auto1}")
    print(f"\n🚗 Automóvil 2:\n   {auto2}")

    # Motos
    separador("CREACIÓN DE MOTOCICLETAS")
    moto1 = Motocicleta("Honda", "CBR600RR", 2022, motor3, 600)
    moto2 = Motocicleta("Ducati", "Monster", 2024, motor4, 937)

    print(f"🏍️  Motocicleta 1:\n   {moto1}")
    print(f"\n🏍️  Motocicleta 2:\n   {moto2}")

    # Prueba auto
    separador("PRUEBA: CHEVROLET CAMARO")
    print("Iniciando prueba del Camaro...")
    auto1.encender()
    auto1.tocar_claxon()
    auto1.abrir_maletero()
    print("\nFinalizando prueba...")
    auto1.apagar()

    # Prueba auto dos
    separador("PRUEBA: TESLA MODEL 3")
    print("Iniciando prueba del Tesla...")
    auto2.encender()
    auto2.abrir_maletero()
    auto2.tocar_claxon()

    # Prueba moto
    separador("PRUEBA: HONDA CBR600RR")
    print("Iniciando prueba de la Honda...")
    moto1.usar_patada_arranque()
    moto1.hacer_caballito()
    print("\nDeteniendo moto...")
    moto1.apagar()

    # Prueba moto 2
    separador("PRUEBA: DUCATI MONSTER")
    print("Iniciando prueba de la Ducati...")
    moto2.encender()
    moto2.hacer_caballito()

    # Resumen cortito
    separador("RESUMEN DE TODOS LOS VEHÍCULOS")
    vehiculos = [auto1, auto2, moto1, moto2]

    for idx, vehiculo in enumerate(vehiculos, 1):
        print(f"\n{idx}. {vehiculo}")


if __name__ == "__main__":
    main()